export { default as App } from './App/App';
export { default as Auth } from './Auth/Auth'
export { default as Layout } from './Layout/Layout';
export { default as Modal } from './Modal/Modal';
export { default as Error } from './Alert/Error/Error';
export { default as Success } from './Alert/Success/Success';
export { default as ManagePost } from './Post/ManagePost/ManagePost';
export { default as CreatePost } from './Post/ManagePost/CreatePost';
export { default as EditPost } from './Post/ManagePost/EditPost';
export { default as DeletePost } from './Post/ManagePost/DeletePost'
export { default as SinglePost } from './Post/SinglePost/SinglePost';
export { default as ViewPosts } from './Post/ViewPosts/ViewPosts';
export { default as Profile } from './Profile/Profile';
export { default as SearchResult } from './SearchResult/SearchResult';