export { default as App } from './App/App';
export { default as Auth } from './Auth/Auth'
export { default as Layout } from './Layout/Layout';
export { default as Error } from './Alert/Error/Error';
export { default as Success } from './Alert/Success/Success';
export { default as CreatePost } from './Post/CreatePost/CreatePost';
export { default as EditPost } from './Post/EditPost/EditPost';
export { default as SinglePost } from './Post/SinglePost/SinglePost';
export { default as ViewPosts } from './Post/ViewPosts/ViewPosts';